### ISSUE TITLE
Text widget causing exception when pasting with keyboard

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/TkZero#19]
Whenever I paste with <kbd>Ctrl</kbd> + <kbd>V</kbd> I get this exception:
```python
Traceback (most recent call last):
  File "E:\TkZero\Examples\Widgets\Text\Text.py", line 32, in <module>
    root.mainloop()
  File "C:\Users\ckyiu\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1422, in mainloop
    self.tk.mainloop(n)
  File "E:\TkZero\TkZero\Text.py", line 77, in _proxy
    result = self.tk.call(cmd)
_tkinter.TclError: text doesn't contain any characters tagged with "sel"
```

**Comment by UnsignedArduino** [comment]
Fixed in https://github.com/UnsignedArduino/TkZero/commit/6a2030a9dccb65f0758e6fa568ba6af84a6e2b8f.
